spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://arara:3306/sample?rewriteBatchedStatements=true
        username: dbuser
        password: dbuser
        max-wait: 1000
        max-active: 50
        test-on-borrow: false
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        database: MySQL

broker:
    bootstrapServer: vmteste007:9092
    zookeeperServer: vmteste007:2181
    partitions: 2
    topic: partitionedTopic
    group-id: sik1
    producer:
        linger-time-ms: 0
        batch-size: 16384
        buffer-size: 33554432
        retries: 2
    consumer:
        enable-auto-commit: false
        auto-commit-interval: 1000
        max-idle: 2000
    session-timeout: 6000
