spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:sample;MODE=MySQL;MVCC=true;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;TRACE_LEVEL_SYSTEM_OUT=1;INIT=RUNSCRIPT from 'classpath:sql/db_init.sql'
        username: dbuser
        password: dbuser
        max-wait: 1000
        max-active: 50
        test-while-idle: true
        test-on-borrow: true
        test-on-return: true
        test-on-connect: true
        validation-interval: 500
        validation-query-timeout: 2000
        validation-query: SELECT 1
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect

broker:
#    bootstrapServer: galo:9092,arara:9092
    bootstrapServer: galo:9092
    zookeeperServer: galo:2181
    partitions: 2
    topic: partitionedTopic
    group-id: sik1
    producer:
        linger-time-ms: 0
        batch-size: 16384
        buffer-size: 33554432
        retries: 2
    consumer:
        enable-auto-commit: false
        auto-commit-interval: 1000
        max-idle: 2000
    session-timeout: 6000
